
[cursor]
blink_interval = 500
blink_timeout = 0
thickness = 0.2
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Underline"

[debug]
render_timer = false

[font]
builtin_box_drawing = true
# draw_bold_text_with_bright_colors = true
size = 11

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[keyboard]
bindings = []

[scrolling]
history = 10000
multiplier = 16

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
blur = false
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.6
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 8
y = 8

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
working_directory = "None"
ipc_socket = true
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[terminal]
